set(_CATKIN_CURRENT_PACKAGE "CANRobot")
set(CANRobot_VERSION "0.0.0")
set(CANRobot_MAINTAINER "abiel <abiel@todo.todo>")
set(CANRobot_PACKAGE_FORMAT "2")
set(CANRobot_BUILD_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(CANRobot_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(CANRobot_BUILDTOOL_DEPENDS "catkin")
set(CANRobot_BUILDTOOL_EXPORT_DEPENDS )
set(CANRobot_EXEC_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(CANRobot_RUN_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(CANRobot_TEST_DEPENDS )
set(CANRobot_DOC_DEPENDS )
set(CANRobot_URL_WEBSITE "")
set(CANRobot_URL_BUGTRACKER "")
set(CANRobot_URL_REPOSITORY "")
set(CANRobot_DEPRECATED "")