set(_CATKIN_CURRENT_PACKAGE "canRobot")
set(canRobot_VERSION "0.0.0")
set(canRobot_MAINTAINER "abiel <abiel@todo.todo>")
set(canRobot_PACKAGE_FORMAT "2")
set(canRobot_BUILD_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(canRobot_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(canRobot_BUILDTOOL_DEPENDS "catkin")
set(canRobot_BUILDTOOL_EXPORT_DEPENDS )
set(canRobot_EXEC_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(canRobot_RUN_DEPENDS "geometry_msgs" "roscpp" "std_msgs")
set(canRobot_TEST_DEPENDS )
set(canRobot_DOC_DEPENDS )
set(canRobot_URL_WEBSITE "")
set(canRobot_URL_BUGTRACKER "")
set(canRobot_URL_REPOSITORY "")
set(canRobot_DEPRECATED "")